config/routes.rb
Rails.application.routes.draw do
  passwordless_for :users

  root "competitions#index"

  resources :competitions, only: [:create, :index, :new]
  resource :my_profile, only: [:edit, :update], controller: :profile

  get "/trophies/:season", season: /\d{4}-\d{4}/, to: "trophies#index", as: :trophies_by_season
  resources :trophies

  get "/leaderboard(/:season)", season: /\d{4}-\d{4}/, to: "leaderboard#show", as: :leaderboard
end

app/models/leaderboard.rb
class Leaderboard
  def initialize(season:)
    @season = season
  end

  def results
    User.with_trophies(season).map do |user|
      LeaderboardResult.new(user, season: season)
    end.sort.reverse
  end

  private

  attr_reader :season
end

app/controllers/leaderboard_controller.rb
class LeaderboardController < ApplicationController
  def show
    @season = if params[:season]
                Season.from_param(params.fetch(:season))
              else
                Season.current
              end
    @leaderboard = Leaderboard.new(season: @season)
  end
end

app/views/leaderboard/show.html.erb
<div class="Subhead">
  <div class="Subhead-heading">Leaderboard for <%= @season.description %> season</div>
  <div class="Subhead-description">
    Starts <%= l @season.start_date, format: :date %>, ends <%= l @season.end_date, format: :date %>
    <%= link_to "View leaderboard for #{@season.previous.description} season", leaderboard_path(@season.previous) %>
  </div>
</div>

<h4>Scoring rules:</h4>
<ul class="pl-6">
  <li>3 points for first place</li>
  <li>2 points for second place</li>
  <li>1 points for third place</li>
  <li>0.5 points for honorable mention</li>
  <li>x2 multiplier for Best of Show place</li>
  <li>0.5 point bonus for high profile competitions</li>
  <li>0 points for club-only competitions</li>
</ul>

<table class="data-table">
  <thead>
    <tr class="bg-gray">
      <td>Brewer Name</td>
      <td>Season Score</td>
    </tr>
  </thead>

  <tbody>
    <% @leaderboard.results.each do |result| %>
      <%= content_tag(:tr, id: "user-#{result.user_id}") do %>
        <%= content_tag(:td) do %>
          <%= link_to result.brewer_name, trophies_path(user_id: result.user_id) %>
        <% end %>

        <%= content_tag(:td, result.score) %>
      <% end %>
    <% end %>
  </tbody>
</table>