config/routes.rb
Rails.application.routes.draw do
  passwordless_for :users

  root "competitions#index"

  resources :competitions, only: [:create, :index, :new]
  resource :my_profile, only: [:edit, :update], controller: :profile

  get "/trophies/:season", season: /\d{4}-\d{4}/, to: "trophies#index", as: :trophies_by_season
  resources :trophies

  get "/leaderboard(/:season)", season: /\d{4}-\d{4}/, to: "leaderboard#show", as: :leaderboard
end

app/models/trophy.rb
class Trophy < ApplicationRecord
  PLACE_CONTEXTS = %w(best_of_show category)

  belongs_to :competition
  belongs_to :subcategory
  belongs_to :user
  delegate :name, :url, to: :competition, prefix: true
  delegate :season, to: :competition
  delegate :bjcp_id, :name, to: :subcategory, prefix: true
  has_one_attached :photo

  validates :bjcp_score, numericality: { greater_than: 0, less_than: 51 }
  validates :competition, presence: true
  validates :place, inclusion: { allow_nil: true, in: 1..4 }
  validates :place_context, inclusion: { allow_nil: true, in: PLACE_CONTEXTS }

  validates :place, presence: true, if: -> { place_context.present? }
  validates :place_context, presence: true, if: -> { place.present? }

  scope :date_descending, -> {
    joins(:competition).merge(Competition.order(date: :desc))
  }
  scope :in_season, ->(season) {
    joins(:competition).merge(Competition.in_season(season))
  }
  scope :placed, -> { where.not(place: nil) }
  scope :placed_in, ->(context) {
    placed.where(place_context: context)
  }

  before_validation do
    # Don't allow blank string for place_context
    self.place_context = place_context.presence
  end

  def leaderboard_score
    return 0 unless competition.gives_leaderboard_points?

    if place
      bos_multiplier = placed_in_best_of_show? ? 2 : 1
      competition_bonus = competition.high_profile? ? 0.5 : 0
      base_leaderboard_score * bos_multiplier + competition_bonus
    else
      0
    end
  end

  def place_description
    if place
      "#{place.ordinalize} in #{place_context.titleize}"
    end
  end

  private

  def base_leaderboard_score
    case place
    when 1 then 3
    when 2 then 2
    when 3 then 1
    when 4 then 0.5
    else
      fail "Unexpected place #{place}"
    end
  end

  def placed_in_best_of_show?
    place_context == "best_of_show"
  end
end

app/controllers/trophies_controller.rb
class TrophiesController < ApplicationController
  before_action :require_user!, except: [:index]

  def index
    @season = if params[:season]
                Season.from_param(params.fetch(:season))
              else
                Season.current
              end
    @user_id = params[:user_id]
    @users = User.named.order(:full_name)

    @competitions_in_season = Competition.in_season(@season).order(:name)
    @subcategories_in_season = Subcategory.has_trophies_in_season(@season).sorted
    @trophies = Trophy.in_season(@season).includes(
      :competition,
      :subcategory,
      :user,
    ).date_descending.with_attached_photo

    @trophies = @trophies.where(user_id: @user_id) if @user_id.present?

    if competition_id = params[:competition_id].presence
      @trophies = @trophies.where(competition_id: competition_id)
    end

    if @subcategory_id = params[:subcategory_id].presence
      @trophies = @trophies.where(subcategory_id: @subcategory_id)
    end
  end

  def new
    @trophy = Trophy.new
  end

  def create
    @trophy = Trophy.new(trophy_params)

    if @trophy.save
      redirect_to trophies_path, notice: "Your trophy was created!"
    else
      render "new"
    end
  end

  def update
    @trophy = Trophy.find(params[:id])

    if @trophy.update(trophy_params)
      redirect_to trophies_path, notice: "Trophy successfully updated!"
    else
      render "new"
    end
  end

  def edit
    @trophy = Trophy.find(params[:id])
  end

  def destroy
    trophy = Trophy.find(params[:id])

    if current_user.can_delete?(trophy) && trophy.destroy
      redirect_to root_path, notice: "Trophy successfully deleted"
    else
      redirect_to root_path, error: "Trophy could not be deleted"
    end
  end

  private

  def trophy_params
    params.require(:trophy).permit(
      :bjcp_score,
      :competition_id,
      :photo,
      :place,
      :place_context,
      :recipe_url,
      :subcategory_id,
    ).merge(user: current_user)
  end
end

app/views/trophies/_form.html.erb
<%= form_for trophy, builder: FormGroupBuilder do |f| %>
  <%= f.form_group :competition_id do %>
    <dt><%= f.label(:competition_id) %></dt>
    <dd class="pb-2">
    <%= f.collection_select :competition_id, Competition.reverse_chronological, :id, :description, {}, { class: "form-select" } %>
    </dd>
    <p>
      If your competition isn't listed, add it
      <%= link_to "here", new_competition_path %>
      first.
    </p>
  <% end %>

  <%= f.form_group :subcategory_id do %>
    <dt><%= f.label(:subcategory_id) %></dt>
    <dd>
      <%= f.collection_select :subcategory_id, Subcategory.sorted, :id, :description, {}, { class: "form-select" } %>
    </dd>
  <% end %>

  <%= f.form_group :bjcp_score do %>
    <dt><%= f.label(:bjcp_score) %></dt>
    <dd>
      <%= f.number_field :bjcp_score, class: "form-control", in: 1..50, step: 1, placeholder: "1-50" %>
    </dd>
  <% end %>

  <%= f.form_group :place do %>
    <dt><%= f.label(:place) %></dt>
    <dd>
      <%= f.collection_select :place, Place.all, :value, :description, { include_blank: "Didn't place" }, { class: "form-select" } %>
      in
      <%= f.collection_select :place_context, Trophy::PLACE_CONTEXTS, :itself, :titleize, { include_blank: "Didn't place" }, { class: "form-select" } %>
    </dd>
  <% end %>

  <%= f.form_group :recipe_url do %>
    <dt><%= f.label(:recipe_url) %></dt>
    <dd>
      <%= f.text_field :recipe_url, class: "form-control" %>
    </dd>
  <% end %>

  <%= f.form_group :photo do %>
    <dt><%= f.label(:photo) %></dt>
    <dd>
      <%= f.file_field :photo, direct_upload: true %>
    </dd>
  <% end %>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/trophies/_table.html.erb
<table class="data-table width-full">
  <thead>
    <tr class="bg-gray">
      <td>Brewer</td>
      <td>Style</td>
      <td>Score</td>
      <td>Competition</td>
      <td>Place</td>
      <td>Links</td>
    </tr>
  </thead>
  <tbody>
    <% @trophies.each do |trophy| %>
      <tr id="trophy-<%= trophy.id %>">
        <td>
          <%= link_to trophy.user.full_name, trophies_by_season_path(@season, user_id: trophy.user.id) %>
        </td>
        <td>
          <%= link_to trophies_by_season_path(@season, subcategory_id: trophy.subcategory_id) do %>
            <span class="Label Label--orange tooltipped tooltipped-e" aria-label="<%= trophy.subcategory_name %>">
              <%= trophy.subcategory_bjcp_id %>
            </span>
          <% end%>
        </td>

        <td>
          <span class="Counter"><%= trophy.bjcp_score %></span>
        </td>

        <td>
          <%= link_to trophy.competition_url do %>
            <%= trophy.competition_name %>
          <% end %>
        </td>

        <td>
          <%= trophy.place_description %>
        </td>

        <td>
          <% if trophy.recipe_url.present? %>
            <%= link_to trophy.recipe_url do %>
              <%= octicon "file", height: 24 %>
            <% end %>
          <% end %>

          <% if trophy.photo.attached? %>
            <%= link_to url_for(trophy.photo) do %>
              <%= octicon "file-media", height: 24 %>
            <% end %>
          <% end %>

          <% if current_user&.can_edit?(trophy) %>
            <%= link_to edit_trophy_path(trophy), "aria-label": "Edit Trophy" do %>
              <%= octicon "pencil", height: 24 %>
            <% end %>
          <% end %>

          <% if current_user&.can_delete?(trophy) %>
            <%= link_to trophy_path(trophy), "aria-label": "Delete Trophy", method: :delete, data: { confirm: "Are you sure you want to delete this trophy?" } do %>
              <%= octicon "trashcan", height: 24 %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/trophies/edit.html.erb
<h2>Update trophy for <%= current_user.full_name %></h2>

<%= render "form", trophy: @trophy %>

app/views/trophies/index.html.erb
<div class="Subhead">
  <div class="Subhead-heading">Trophies</div>
  <div class="Subhead-actions">
    <%= content_tag(:a, "Add Trophy", class: "btn btn-primary", href: "/trophies/new") %>
  </div>
</div>

<div class="tabnav">
  <nav class="tabnav-tabs">
    <% Competition.seasons_descending.each do |season| %>
      <% selected_tab_class = @season == season ? " selected" : "" %>
      <%= link_to season.description, trophies_by_season_path(season.to_param), class: "tabnav-tab#{selected_tab_class}" %>
    <% end %>
  </nav>
</div>

<%= form_tag nil, method: :get, class: "mb-4" do %>
  <%= select_tag :competition_id, options_from_collection_for_select(@competitions_in_season, :id, :name, params[:competition_id]), class: "form-select", onchange: "this.form.submit()", prompt: "All Competitions" %>
<% end %>

<%= form_tag nil, method: :get, class: "mb-4" do %>
  <%= select_tag :user_id, options_from_collection_for_select(@users, :id, :full_name, @user_id), class: "form-select", onchange: "this.form.submit()", prompt: "All Worts" %>
<% end %>

<%= form_tag nil, method: :get, class: "mb-4" do %>
  <%= select_tag :subcategory_id, options_from_collection_for_select(@subcategories_in_season, :id, :description, @subcategory_id), class: "form-select", onchange: "this.form.submit()", prompt: "All Categories" %>
<% end %>

<% if @trophies.any? %>
  <%= render "table", trophies: @trophies %>
<% else %>
  <div class="blankslate">
    <h3>No trophies yet</h3>
    <p>But we're on it</p>
  </div>
<% end %>

app/views/trophies/new.html.erb
<h2>Add a trophy for <%= current_user.full_name %></h2>

<%= render "form", trophy: @trophy %>