config/routes.rb
Rails.application.routes.draw do
  passwordless_for :users

  root "competitions#index"

  resources :competitions, only: [:create, :index, :new]
  resource :my_profile, only: [:edit, :update], controller: :profile

  get "/trophies/:season", season: /\d{4}-\d{4}/, to: "trophies#index", as: :trophies_by_season
  resources :trophies

  get "/leaderboard(/:season)", season: /\d{4}-\d{4}/, to: "leaderboard#show", as: :leaderboard
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Worts Trophy Case</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class="container-md">
      <h1>Worts Trophy Case</h1>

      <nav class="menu" aria-label="Menu">
        <%= nav_link "/competitions" do %>
          <%= octicon "law" %>
          Competitions
        <% end %>

        <%= nav_link "/leaderboard" do %>
          <%= octicon "graph" %>
          Leaderboard
        <% end %>

        <%= nav_link "/trophies" do %>
          <%= octicon "star" %>
          Trophies
        <% end %>

        <% if current_user %>
          <%= nav_link edit_my_profile_path do %>
            <%= octicon "person" %>
            My Profile
          <% end %>
        <% end %>

        <%= nav_link "http://wort.org" do %>
          <%= octicon "home" %>
          Worts Home
        <% end %>
      </nav>

      <% if flash[:error] %>
        <div class="flash flash-error my-3"><%= flash[:error].html_safe %></div>
      <% end %>

      <% if flash[:notice] %>
        <div class="flash flash-success my-3"><%= flash[:notice].html_safe %></div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>